version: 0.2
phases:
  pre_build:
    commands:
      - echo pre_build started on `date`
      - echo Logging in to Amazon ECR...
      - IMAGE_URI_NODE=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME_NODE
      - IMAGE_TAG=`cat docker-compose.prod.yml |grep "image:" |awk -F':' '{print $3}'`
      - echo $IMAGE_TAG
      - sed -i "s/ECR_URI/$IMAGE_URI_NODE/g" docker-compose.prod.yml
      - cat docker-compose.prod.yml
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - docker-compose build
        #      - docker tag fargate-deploy-nginx:$IMAGE_TAG $IMAGE_URI_NODE
  post_build:
    commands:
      - docker push $IMAGE_URI_NODE:$IMAGE_TAG
      - echo '[{"name":"nnode","imageUri":"__URI_NODE__"}]' > imagedef.json
      - sed -ie "s@__URI_NODE__@${IMAGE_URI_NODE}:${IMAGE_TAG}@" imagedef.json
artifacts:
  files:
    - imagedef.json
