version: '3'
services:
 app:
   image: ECR_URL:v1.0.0
   env_file: ./src/production.env
   environment:
     - TZ=Asia/Tokyo
   tty: true
   ports:
     - '80:3000'
   command: npm start
   restart: always
